### ISSUE TITLE
Spacing issue on landing page

### ISSUE THREAD

**Issue by AltriusRS** [kniffen/TruckSim-Telemetry-Docs#1]
Hi, just noticed a slight spacing issue on the landing page where it says the following:

![image](https://user-images.githubusercontent.com/63651404/175833433-e293eae1-f7ec-44c2-9fc2-6318d4c10672.png)

There is a space there in the document, but it does not appear to be properly spaced on the website. I would like to suggest it is due to the use of an anchor?

either way it is a low-priority issue so, no rush :)

**Comment by kniffen** [comment]
This is a known issue with how [Docsify](https://docsify.js.org) renders headings.
Where it adds an anchor element to be able to link to that position on the page.

The problem occurs when you have a link inside the heading, making it close the heading's anchor tag before the link's.
Causing there to be two anchor elements next to each other with no space in-between.

I have known about this issue for a while, but not been able to find a good solution.

**Comment by kniffen** [comment]
Temporarily solved with a "hack"
Replacing the space with a [Tag space emoji](https://emojipedia.org/tag-space/)
However it does mess up the links to the headings
